import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../component/Layout/Header/Header';
import TeamSelection from '../component/Asset/Asset';
import styles from '../styles/Home.module.css';
import {
	ApolloClient,
	InMemoryCache,
	ApolloProvider,
	gql,
} from '@apollo/client';
import Asset from '../component/Asset/Asset';

const Home: NextPage = () => {
	const client = new ApolloClient({
		uri: 'https://analytics-api.herokuapp.com/analytics',
		cache: new InMemoryCache(),
	});
	return (
		<ApolloProvider client={client}>
			<div className={styles.container}>
				<Head>
					<title>Asalytics</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/card_logo.svg' />
				</Head>
				<Header />
				<main className={styles.main}>
					<h2 style={{ marginTop: 42, marginBottom: 42 }}>
						List of Algorand Standard Assets <br /> on ASAlytics
					</h2>
					{/* <TeamSelection /> */}
					<Asset />
				</main>
			</div>
		</ApolloProvider>
	);
};

export default Home;
