import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import TeamSelection from '../component/TeamSelection';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<header className={styles.header}>
				<Image src='/Header Logo.png' alt='Logo' width={150} height='62px' />
				<button className={styles.button}>ANALYZE ASAs</button>
			</header>

			<main className={styles.main}>
				<h2 style={{ marginTop: 42, marginBottom: 42 }}>
					List of Algorand Standard Assets <br /> on ASAlytics
				</h2>
				<TeamSelection />
			</main>
		</div>
	);
};

export default Home;
